### ISSUE TITLE
about driving.caffemodel fetch 

### ISSUE THREAD

**Issue by killerjian007** [alexgkendall/SegNet-Tutorial#11]
Hi, @alexgkendall 
Thanks for your excellent work!
Now I want to download the driving.caffemodel in Example_Models/driving_web_demo/,  but find the lfs data quota is exceeded,  Is there any alternative way to access the model file?

Here is what I've got after running git lfs fetch/pull:
> Git LFS: (0 of 1 files) 0 B / 112.35 MB
> This repository is over its data quota. Purchase more data packs to restore access.
> Docs: https://help.github.com/articles/purchasing-additional-storage-and-bandwidth-for-a-personal-account/

Thanks.

**Comment by alexgkendall** [comment]
@killerjian007, 

Sorry, I'm aware of this issue and will fix it when I am back in the office next week (January 11).

Alex

**Comment by killerjian007** [comment]
@alexgkendall 
i am sorry to interrupt you , about the problem mentioned above, have you already solved it? i really need your help. really appreciate if you can reply soon.

**Comment by alexgkendall** [comment]
Hi @killerjian007 

I've just created a SegNet Model Zoo!

https://github.com/alexgkendall/SegNet-Tutorial/blob/master/Example_Models/segnet_model_zoo.md

You will now be able to download the model, and future models which I release, from here. Sorry for unexpectedly running over my LFS data quota!

Alex

**Comment by amiltonwong** [comment]
Hi, @alexgkendall ,
If I use the following command to compute BN statistics:
python /SegNet/Scripts/compute_bn_statistics.py /SegNet/Example_Models/segnet_model_driving_webdemo.prototxt /SegNet/Example_Models/segnet_weights_driving_webdemo.caffemodel /SegNet/Models/Inference/

I came across the following error :

Building BN calc net...
Traceback (most recent call last):
  File "/SegNet/Scripts/compute_bn_statistics.py", line 171, in <module>
    testable_msg = make_testable(args.train_model)
  File "/SegNet/Scripts/compute_bn_statistics.py", line 35, in make_testable
    text_format.Merge(train_str, train_net)
  File "/root/anaconda/lib/python2.7/site-packages/google/protobuf/text_format.py", line 265, in Merge
    return MergeLines(text.split('\n'), message)
  File "/root/anaconda/lib/python2.7/site-packages/google/protobuf/text_format.py", line 298, in MergeLines
    _ParseOrMerge(lines, message, True)
  File "/root/anaconda/lib/python2.7/site-packages/google/protobuf/text_format.py", line 229, in _ParseOrMerge
    _MergeField(tokenizer, message, allow_multiple_scalars)
  File "/root/anaconda/lib/python2.7/site-packages/google/protobuf/text_format.py", line 382, in _MergeField
    _MergeField(tokenizer, sub_message, allow_multiple_scalars)
  File "/root/anaconda/lib/python2.7/site-packages/google/protobuf/text_format.py", line 382, in _MergeField
    _MergeField(tokenizer, sub_message, allow_multiple_scalars)
  File "/root/anaconda/lib/python2.7/site-packages/google/protobuf/text_format.py", line 356, in _MergeField
    message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 1605:5 : Message type "caffe.ArgMaxParameter" has no field named "axis".


Any suggestion?

**Comment by alexgkendall** [comment]
Hi @amiltonwong , you don't need to compute bn statistics for the demo model, it's already done. As for the error it looks like you are not running the SegNet version of caffe in your python script?
