### ISSUE TITLE
pre-trained model on the KITTI dataset

### ISSUE THREAD

**Issue by xmaster302** [alexgkendall/SegNet-Tutorial#12]
Hi, @alexgkendall, could you please release your pre-trained model on the KITTI dataset?

**Comment by alexgkendall** [comment]
I haven't trained a model on the Kitti dataset, it is quite small. But I've made a model zoo page where I will be releasing more models shortly:

https://github.com/alexgkendall/SegNet-Tutorial/blob/master/Example_Models/segnet_model_zoo.md
