### ISSUE TITLE
bn_param not found

### ISSUE THREAD

**Issue by arushk1** [alexgkendall/SegNet-Tutorial#13]
When running : 

python Scripts/webcam_demo.py --model Example_Models/driving_web_demo/driving.prototxt --weights Models/Training/segnet_basic_iter_3000.caffemodel --colours Scripts/camvid12.png

Where The weights are the ones trained using the 'segnet_basic_solver', I get the following error. Anything I can change to get it working?

[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 47:12: Message type "caffe.LayerParameter" has no field named "bn_param".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0111 13:43:12.378470 11185 upgrade_proto.cpp:928] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: Example_Models/driving_web_demo/driving.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by ieted** [comment]
I met the same problem. Haven't got a solution yet.

**Comment by arushk1** [comment]
The path to your caffe installation is wrong. Try adding an extra '/' to the end of the path. This issue is solved.

**Comment by ieted** [comment]
@arushk1 Thanks. It also works for my situation.

**Comment by DinhOsh** [comment]
I got the same error but I am not so good at python.
Could you explain more details about its solution?
This is my code what I have tried.

`caffe_root = '/home/my_ubuntu/caffe/'
sys.path.insert(0, caffe_root + 'python/')
import caffe

model_ = "./segnet_model_driving_webdemo.prototxt"
weights_ = "./segnet_weights_driving_webdemo.caffemodel"
colours_ = "./camvid12.png"

net = caffe.Net(model_, weights_, caffe.TEST)
`
The model and weight files are located in the same folder with main.py.

**Comment by beihaidao** [comment]
@arushk1 may you please explain more details about how to solve this problem? add '/' in where?
thinks a lot.
