### ISSUE TITLE
Segnet server down

### ISSUE THREAD

**Issue by gi097** [alexgkendall/SegNet-Tutorial#131]
Hi,

When I try to access the SegNet website to download the models, I can see that the server is down. Are there any alternative download links for the pretrained models?

Regards,
Giovanni

**Comment by alexgkendall** [comment]
Hi Giovanni, our server at cambridge is currently down for maintenance for
a few days, should be up again later this week. Sorry about this!

**Comment by gi097** [comment]
Okay thank you! Have a good day.
