### ISSUE TITLE
How to Label my own images?

### ISSUE THREAD

**Issue by arushk1** [alexgkendall/SegNet-Tutorial#14]
I downloaded the interact labeler from the u-cambridge website, but I can't get it to run. I know it works on Windows, but it shows MSVCR71.dll is missing. 

Can you help me on the solution?

**Comment by alexgkendall** [comment]
Unfortunately I'm not familiar with this software - you'll have to contact the original authors.

**Comment by arushk1** [comment]
How did you label the CamVid dataset?
