### ISSUE TITLE
Running error (Live Demo)

### ISSUE THREAD

**Issue by amiltonwong** [alexgkendall/SegNet-Tutorial#15]
Dear @alexgkendall 

I'm following the "Getting Started with Live Demo" section, but it fails.
Please see the running error as follows:

=================================================

root@milton-Desktop:/SegNet# python Scripts/webcam_demo.py --model Example_Models/segnet_model_driving_webdemo.prototxt --weights Example_Models/segnet_weights_driving_webdemo.caffemodel --colours /Scripts/camvid12.png

libprotobuf ERROR google/protobuf/text_format.cc:172] Error parsing text-format caffe.NetParameter: 1605:9: Message type "caffe.ArgMaxParameter" has no field named "axis".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0114 09:55:46.792676  7218 upgrade_proto.cpp:928] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: Example_Models/segnet_model_driving_webdemo.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)

=================================================

Any suggestion to fix this error?

Thanks~
Milton

**Comment by arushk1** [comment]
There might be a problem with your caffe path. Did you add an extra '/' after 'caffe-segnet'?

**Comment by alexgkendall** [comment]
It appears you are not running the latest version of SegNet. Make sure your repository clone is up to date (and has the argmax axis commit which I added)? And as @arushk1 said, ensure your path is correct and you are running the SegNet version of caffe.
