### ISSUE TITLE
Have I missed something or labels are black?!!

### ISSUE THREAD

**Issue by sezan92** [alexgkendall/SegNet-Tutorial#150]
Hello, i was checking the camvid folder in your repo. I found the annotations in the annot folders are all black.. I don't know , am i missing something?

**Comment by mf27** [comment]
That's because annotations only use integer indexes for every class, they are not intended for visualization. Colours in `Scripts/camvid12.png` (every colour corresponds to a particular class) are used for visualization purpose.
