### ISSUE TITLE
How to Label my own images?

### ISSUE THREAD

**Issue by arushk1** [alexgkendall/SegNet-Tutorial#16]
I have my own images that I wish to annotate. Which tool did you use to label your dataset? 

1) During training, in 'segnet_train.prototxt', the final output is of 11 classes, but in the 'segnet_model_driving_webdemo.prototxt', the final output is 12 classes. I don't understand why is that. 

2) Secondly, the labels of the images in the CamVid contain a different shade of grey for every class. Can you list the classes and the corresponding grey labels for them?

**Comment by alexgkendall** [comment]
I didn't generate the CamVid dataset - you will need to contact the authors directly for more information.

1) The webdemo has an additional class (road marking)

2) For the 11 class model, the corresponding codes in order from grey index 0-10 are:
Sky, Building, Pole, Road, Pavement, Tree, SignSymbol, Fence, Car, Pedestrian, Bicyclist
See ```https://github.com/alexgkendall/SegNet-Tutorial/blob/master/Scripts/test_segmentation_camvid.py``` for more details.

**Comment by arushk1** [comment]
So, if I want to train Segnet with the Road marking, I should just increase the output of the final layer to 12. in the 'segnet_train.prototxt' right?

**Comment by alexgkendall** [comment]
That's right! You can download the original CamVid dataset which has 32 classes from memory, including road marking.

**Comment by jorgyz** [comment]
If you're still looking for an annotation tool to label your training data, I came across this one written in Javascript that seems to work well.

**Comment by arushk1** [comment]
@jorgyz Which one?

**Comment by jorgyz** [comment]
whoops!  the link is github.com/kyamagu/js-segment-annotator. Sorry about that

**Comment by defenceVT** [comment]
@arushk1  have you solve the problem? i have downloads the CamVid dataset , and it contain 32 classes labels, the format of the dataset is RGB, but the data trained for segnet is single channel. how do you solve it ?
thx~
kevin

**Comment by jay98** [comment]
I have the same question as @defenceVT , @arushk1 if you could tell how you did it, it would be a great help !!

Thank You,
Jay
