### ISSUE TITLE
Issue while running test_segmentation_camvid.py

### ISSUE THREAD

**Issue by aseembits93** [alexgkendall/SegNet-Tutorial#19]
I get the following error while running test_segmentation_camvid.py on segnet trained model. 
rgb_gt[:,:,0] = r_gt/255.0
ValueError: could not broadcast input array from shape (4,1,360,480) into shape (360,480)
I dont get this error when i run on segnet basic trained model.

**Comment by MahmoudElkhateeb** [comment]
@aseembits93 I faced the same problem, I solved it by changing the batch_size at inference.prototxt

**Comment by aseembits93** [comment]
Thanks @MahmoudElkhateeb !

**Comment by MahmoudElkhateeb** [comment]
Welcome @aseembits93 !  Does it work with you too?

**Comment by aseembits93** [comment]
I'll try it and get back to you soon!

**Comment by aseembits93** [comment]
@MahmoudElkhateeb It is working fine! Thanks!
