### ISSUE TITLE
about tutorial on Bayesian SegNet

### ISSUE THREAD

**Issue by amiltonwong** [alexgkendall/SegNet-Tutorial#2]
Hi, @alexgkendall 
It is so great to see the tutorial on Bayesian SegNet will be coming soon.

According to Bayesian SegNet paper, monte-carlo sampling and variational inference are required. Did you re-implement the those parts such as variational inference or apply other third-party tools?

Best~
Milton

**Comment by alexgkendall** [comment]
The entire Bayesian SegNet system was implemented in Caffe.

**Comment by alexgkendall** [comment]
The Bayesian SegNet tutorial is here:  http://mi.eng.cam.ac.uk/projects/segnet/tutorial.html#bayes_segnet
