### ISSUE TITLE
Scripts/test_bayesian_segnet.py

### ISSUE THREAD

**Issue by tsingjinyun** [alexgkendall/SegNet-Tutorial#23]
when run test_bayesian_segnet.py follow the tutour,make following error
Traceback (most recent call last):
  File "Scripts/test_bayesian_segnet.py", line 57, in <module>
    out = net.forward_all(data=input_image)
  File "/home/caffe/dl/segment/caffe-segnet/python/caffe/pycaffe.py", line 168, in _Net_forward_all
    outs = self.forward(blobs=blobs, **batch)
  File "/home/caffe/dl/segment/caffe-segnet/python/caffe/pycaffe.py", line 87, in _Net_forward
    raise Exception('Input blob arguments do not match net inputs.')
Exception: Input blob arguments do not match net inputs.

someone else run the same problem?

**Comment by alexgkendall** [comment]
What have you set the batch size (sample size) to in your model? Also, just checking you are using the inference model?

**Comment by tsingjinyun** [comment]
$ ./caffe-segnet/build/tools/caffe train -solver Models/bayesian_segnet_basic_solver.prototxt
$ python Scripts/compute_bn_statistics.py Models/bayesian_segnet_basic_train.prototxt Models/Training/bayesian_segnet_basic_iter_10.caffemodel Models/Inference/
$ python Scripts/test_bayesian_segnet.py --model Models/bayesian_segnet_basic_inference.prototxt --weights Models/Inference/test_weights.caffemodel --colours Scripts/camvid11.png  --data  CamVid/test.txt

The batch size is the same as your tutour, and run the other sample is ok,but the bayesian segment throw out exception as mentioned. and thank your helps

**Comment by alexgkendall** [comment]
When using the ```test_bayesian_segnet.py``` the script loads the data for you, so you can't use the DenseImageDataLayer. Your model should begin with something like these lines:
input: "data"
input_dim: 8 # Set this to your sample size
input_dim: 3
input_dim: 360
input_dim: 480


As an example: https://github.com/alexgkendall/SegNet-Tutorial/blob/master/Example_Models/bayesian_segnet_basic_camvid.prototxt

The webcam demo doesn't support bayesian segnet at this time.

Cheers,
Alex

**Comment by tsingjinyun** [comment]
as i write before, first train the caffemodel, then  batch normalisation statistic the trained caffemodel, finally use test_weights.caffemodel, but i debug the test_bayesian_segnet.py ,and find that caffe net initial may have some wrong, is there anything i miss?
