### ISSUE TITLE
CUDA Error: GPU out of memory with batch_size = 1.

### ISSUE THREAD

**Issue by dongleecsu** [alexgkendall/SegNet-Tutorial#25]
Hi @alexgkendall , thank you so much for your guide.
I followed the instructions on [http://mi.eng.cam.ac.uk/projects/segnet/tutorial.html ](url) to train the SegNet. But when I opened up a terminal and ran the commands:
`./SegNet/caffe-segnet/build/tools/caffe train -gpu 0 -solver /SegNet/Models/segnet_basic_solver.prototxt`
An error occurred:
![batch_size_1_error](https://cloud.githubusercontent.com/assets/13414927/13427438/f682ea04-dfee-11e5-8558-2eaafe86f1b6.png)
It seems that the GPU is out of memory(batch_size = 1, so Memory required for data: 410926132).
So I checked the GPU with the command:
`nvidia-smi`
Result:
![smi](https://cloud.githubusercontent.com/assets/13414927/13427628/4303767c-dff0-11e5-8151-84a0797e7a8e.png)
My GPU is GT 720 with 1G memory. Though the memory is small, it is much bigger than 245MB + 410MB(data required memory above) = 655MB.

So I would like to ask your advice for this issue :-)
Thank you!

**Comment by alexgkendall** [comment]
I believe the data required (410MB) is just for the weights/data. Caffe requires additional memory for the solver and gradient parameters. You might struggle on a 1GB GPU I'm afraid!

**Comment by dongleecsu** [comment]
Thank you @alexgkendall . I tried on another GPU and figured it out.

**Comment by rshanor** [comment]
@dongleecsu was the GPU your problem? I am trying to run the examples on a 4GB GTX980 with no luck yet, also setting the batch size to 1.

**Comment by dongleecsu** [comment]
@rshanor were there any other programs using the GPU at the same time? You can check the GPU memory usage with `nvidia-smi`. I tried to run the Segnet basic(batch_size=1) on a 12G Titan, and everything was OK.

**Comment by rshanor** [comment]
@dongleecsu thanks. I was finally able to get some results by downsizing the images. Curiously, with 240x180 images, I can run with a batch size of 7...

**Comment by tsingjinyun** [comment]
@rshanor ，if you use  4GB GTX980 && batch:=1, you can restart computer and just run this code ,it maybe ok, i run into this problem

**Comment by mrgloom** [comment]
Same https://github.com/alexgkendall/caffe-segnet/issues/21

**Comment by LordOfAshes** [comment]
@rshanor  Did you make additional modifications after resizing the images? With 240x180 images I get an error
 upsample_layer.cpp:63] Check failed: bottom[0]->height() == bottom[1]->height() (23 vs. 12)

**Comment by mitalbert** [comment]
@LordOfAshes you should change upsample_w and upsample_h in your prototxt training file.
