### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by rshanor** [alexgkendall/SegNet-Tutorial#26]
Hi, 

I am trying to work my way through the SegNet tutorial. During the training step, I right away get the error 'error == cudaSuccess (2 vs. 0)  out of memory'. I am trying to train on my 4GB GTX980. I am have tried both SegNet and SegNet basic, with batch size as small as just 1. Is there anything else that may be causing this error? Or is my graphics card just insufficient.

Thanks,
Rick

**Comment by mrgloom** [comment]
See this https://github.com/alexgkendall/caffe-segnet/issues/21

**Comment by rshanor** [comment]
I ended up having to downsample the images by half, and can now run with batch size 7.

**Comment by mrgloom** [comment]
Can you post resulting *.prototxt file?

I tried to reduce dimensions of images but still have errors.
https://gist.github.com/mrgloom/f0972272938adfc44163

**Comment by rshanor** [comment]
Can you repost your errors? I will try and help you debug. All I changed were upsample parameters, as well as the prediction outputs.
