### ISSUE TITLE
Problem in CPU mode

### ISSUE THREAD

**Issue by Sumilak21111994** [alexgkendall/SegNet-Tutorial#27]
I am using caffe in CPU mode. I have made the necessary changes in the solver file. However what are the changes that need to be made on this terminal command?
/SegNet/caffe-segnet/build/tools/caffe train -gpu 0 -solver /SegNet/Models/segnet_solver.prototxt

**Comment by mrgloom** [comment]
remove `-gpu 0`

**Comment by Sumilak21111994** [comment]
Now it says this
~$ ./SegNet/caffe-segnet/build/tools/caffe train -solver /SegNet/Models/segnet_solver.prototxt
F0311 22:06:03.536821 14962 io.cpp:34] Check failed: fd != -1 (-1 vs. -1) File not found: /SegNet/Models/segnet_solver.prototxt
*** Check failure stack trace: ***
    @     0x7fa51ae2d5cd  google::LogMessage::Fail()
    @     0x7fa51ae2f433  google::LogMessage::SendToLog()
    @     0x7fa51ae2d15b  google::LogMessage::Flush()
    @     0x7fa51ae2fe1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fa51b288618  caffe::ReadProtoFromTextFile()
    @           0x407c4c  train()
    @           0x405ac8  main
    @     0x7fa51a2bea40  __libc_start_main
    @           0x405fe9  _start
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by mrgloom** [comment]
Seems you need to change `/SegNet/Models/segnet_solver.prototxt` to real absolute path.

**Comment by Sumilak21111994** [comment]
so I changed it to absolute path but now it says it cannot find file segnet_train.prototxt
 ./SegNet/caffe-segnet/build/tools/caffe train -solver ./SegNet/Models/segnet_solver.prototxt
I0311 22:26:32.864996 15055 caffe.cpp:117] Use CPU.
I0311 22:26:32.865955 15055 caffe.cpp:121] Starting Optimization
I0311 22:26:32.866209 15055 solver.cpp:32] Initializing solver from parameters: 
test_iter: 1
test_interval: 10000000
base_lr: 0.001
display: 20
max_iter: 40000
lr_policy: "step"
gamma: 1
momentum: 0.9
weight_decay: 0.0005
stepsize: 10000000
snapshot: 1000
snapshot_prefix: "/SegNet/Models/Training/segnet"
solver_mode: CPU
net: "/SegNet/Models/segnet_train.prototxt"
test_initialization: false
I0311 22:26:32.866503 15055 solver.cpp:70] Creating training net from net file: /SegNet/Models/segnet_train.prototxt
F0311 22:26:32.866613 15055 io.cpp:34] Check failed: fd != -1 (-1 vs. -1) File not found: /SegNet/Models/segnet_train.prototxt
*** Check failure stack trace: ***
    @     0x7f14903ac5cd  google::LogMessage::Fail()
    @     0x7f14903ae433  google::LogMessage::SendToLog()
    @     0x7f14903ac15b  google::LogMessage::Flush()
    @     0x7f14903aee1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f1490807618  caffe::ReadProtoFromTextFile()
    @     0x7f14908151f6  caffe::ReadNetParamsFromTextFileOrDie()
    @     0x7f14907eb5df  caffe::Solver<>::InitTrainNet()
    @     0x7f14907ec7be  caffe::Solver<>::Init()
    @     0x7f14907ec986  caffe::Solver<>::Solver()
    @           0x40f660  caffe::GetSolver<>()
    @           0x407d1a  train()
    @           0x405ac8  main
    @     0x7f148f83da40  __libc_start_main
    @           0x405fe9  _start
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by mrgloom** [comment]
Follow the tutorial http://mi.eng.cam.ac.uk/projects/segnet/tutorial.html
You also need to change path `/SegNet/Models/segnet_train.prototxt` inside `.prototxt`
