### ISSUE TITLE
Classification in C++

### ISSUE THREAD

**Issue by uschmelmer** [alexgkendall/SegNet-Tutorial#28]
Hi,
i am looking for a C++ example to classifiy an OpenCV mat (like the webcam demo)
Could you describe or document the corresponding C++ caffe calls?
Thank you and best Regards,
Udo

**Comment by rshanor** [comment]
I am trying to figure this out as well right now? Have you had any luck?

**Comment by canerhazirbas** [comment]
You can find examples in the following links:

https://github.com/BVLC/caffe/blob/master/examples/cpp_classification/classification.cpp
https://gist.github.com/onauparc/dd80907401b26b602885

**Comment by montekristo1946** [comment]
You happen to assemble a working example?

**Comment by TimoSaemann** [comment]
You might find the script "test_segmentation.cpp" in the script folder helpful.
https://github.com/alexgkendall/SegNet-Tutorial/blob/master/Scripts/test_segmentation.cpp
