### ISSUE TITLE
Error on shared libraries

### ISSUE THREAD

**Issue by Crefeda** [alexgkendall/SegNet-Tutorial#3]
I am trying to use segnet in CPU only mode:

I tried ./caffe-segnet/build/tools/caffe train --solver=Models/segnet_basic_solver.prototxt

And I got the following error:
./caffe-segnet/build/tools/caffe: error while loading shared libraries: liblmdb.so: cannot open shared object file: No such file or directory

**Comment by alexgkendall** [comment]
CPU training is going to be painfully slow, but if you would really like to try you should follow the tutorial. The only difference is that you will need to change the line in the solver prototexts to:
solver_mode: CPU

The error you are reporting looks like a problem with your Caffe set up - you may find more helpful answers from the main Caffe github page.

**Comment by Crefeda** [comment]
Yes I got it to work on CPU at the moment. The CPU has 48 cores so I am hoping that it will run okay. I raised another issue. This one can be closed.
