### ISSUE TITLE
 class_weighting

### ISSUE THREAD

**Issue by langbin2014** [alexgkendall/SegNet-Tutorial#31]
class_weighting: 0.2595
    class_weighting: 0.1826
    class_weighting: 4.5640
    class_weighting: 0.1417
    class_weighting: 0.9051
    class_weighting: 0.3826
    class_weighting: 9.6446
    class_weighting: 1.8418
    class_weighting: 0.6823
    class_weighting: 6.2478
    class_weighting: 7.3614
How do I calculate them？Please help me.

**Comment by canerhazirbas** [comment]
You can check out the formula here: http://arxiv.org/pdf/1411.4734v4.pdf

> _we weight each pixel by `αc = median freq/freq(c)` where freq(c) is the number of pixels of class c divided by the total number of pixels in images where c is present, and median freq is the median of these frequencies. _

**Comment by langbin2014** [comment]
Thank you very much.
