### ISSUE TITLE
Feedback to the developers

### ISSUE THREAD

**Issue by Almo1982** [alexgkendall/SegNet-Tutorial#38]
Hi all,
thank you very much for this great tutorial, i worked it through successfully with one exception at the end:
File "./SegNet/Scripts/test_segmentation_camvid.py", line 77, in <module>
    rgb_gt[:,:,1] = g_gt/255.0
ValueError: could not broadcast input array from shape (3,1,360,480) into shape (360,480)

when i comment these 3 lines out in the corresponding py-file the code runs through, but then i get a black picture :-)

I have to say i didn't train the net for the whole 10000 iterations, i stopped after 1000, just to take a first look if it works anyway. I don't think this error has to do with this, or? This seems more like an array conversion problem. Have you heard about this issue before?

One more note from my side:
in your tutorial you have a little clerical error in these two lines:

python /Seg**n**et/Scripts/compute_bn_statistics.py /SegNet/Models/segnet_train.prototxt /SegNet/Models/Training/segnet_iter_10000.caffemodel /Seg**n**et/Models/Inference/  # compute BN statistics for SegNet
python /Seg**n**et/Scripts/compute_bn_statistics.py /SegNet/Models/segnet_basic_train.prototxt /SegNet/Models/Training/segnet_basic_iter_10000.caffemodel /Seg**n**et/Models/Inference/  # compute BN statistics for SegNet-Basic

the marked "n"s should be written in upper case, just for information ;-)

Thank you again, i made a big progress with your tutorial for my own application.

Regards
Stefan

**Comment by yiyao35** [comment]
Seems your label images have 3 channels, try single channel gray images.

**Comment by Almo1982** [comment]
Thank you for your Feedback...but this is the original Image data that Comes with the tutorial, so i am a Little bit confused. 

Does it work for others?

**Comment by Timo-hab** [comment]
I got the same error. Have you trained with batchsize=3 ? 
I have the batch size changed in segnet_basic_inference.prototxt to 1 prior to testing.

**Comment by Almo1982** [comment]
Its working now, i had to change the batch size in the interference.prototxt to 1! Thanks

**Comment by saviogeorge** [comment]
I had the same issue and by changing the batch size = 3 to 1 in segnet_inference.prototxt helped me, to solve the issue
