### ISSUE TITLE
"caffe.LayerParameter" has no field named "dense_image_data_param".

### ISSUE THREAD

**Issue by Crefeda** [alexgkendall/SegNet-Tutorial#4]
I got the following error when trying to run SegNet basic using only CPU.  Basically the error says there is no field name called  "dense_image_data_param". which it reads from segnet_basic_train.prototxt?

Error Output:

I1201 14:55:25.982578  4028 caffe.cpp:177] Use CPU.
I1201 14:55:25.983726  4028 solver.cpp:48] Initializing solver from parameters: 
test_iter: 1
test_interval: 10000000
base_lr: 0.1
display: 20
max_iter: 10000
lr_policy: "step"
gamma: 1
momentum: 0.9
weight_decay: 0.0005
stepsize: 10000000
snapshot: 1000
snapshot_prefix: "/home/crefeda/Desktop/SegNet/Models/Training/segnet_basic"
solver_mode: CPU
net: "/home/crefeda/Desktop/SegNet/Models/segnet_basic_train.prototxt"
test_initialization: false
I1201 14:55:25.984231  4028 solver.cpp:91] Creating training net from net file: /home/crefeda/Desktop/SegNet/Models/segnet_basic_train.prototxt
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 7:26: Message type "caffe.LayerParameter" has no field named "dense_image_data_param".
F1201 14:55:25.984504  4028 upgrade_proto.cpp:68] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /home/crefeda/Desktop/SegNet/Models/segnet_basic_train.prototxt
*** Check failure stack trace: ***
    @     0x7f9e2a9e4daa  (unknown)
    @     0x7f9e2a9e4ce4  (unknown)
    @     0x7f9e2a9e46e6  (unknown)
    @     0x7f9e2a9e7687  (unknown)
    @     0x7f9e2ae712ae  caffe::ReadNetParamsFromTextFileOrDie()
    @     0x7f9e2ae5531b  caffe::Solver<>::InitTrainNet()
    @     0x7f9e2ae563fc  caffe::Solver<>::Init()
    @     0x7f9e2ae56709  caffe::Solver<>::Solver()
    @     0x7f9e2ad5a883  caffe::Creator_SGDSolver<>()
    @           0x40e35e  caffe::SolverRegistry<>::CreateSolver()
    @           0x4076cb  train()
    @           0x405651  main
    @     0x7f9e29cf2ec5  (unknown)
    @           0x405d61  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by alexgkendall** [comment]
Are you sure you are using the code for SegNet? https://github.com/alexgkendall/caffe-segnet

**Comment by Crefeda** [comment]
Yes, just realized my error. Have reinstalled from the link provided thanks. It works now. Thank you so much.

**Comment by annie-z** [comment]
I am having this exact same problem. @Crefeda how did you end up resolving this?

**Comment by sirim** [comment]
I suppose this has to be with the version of the caffe use are using. I had similar issue when I tried to compile Segnet_tutorial (https://github.com/alexgkendall/SegNet-Tutorial) with newer version of caffe. The latest version of caffe-master doesn't have "dense_image_data_param" as a layer parameter. I heard the old prototxt are automatically upgraded when compiled with new version of caffe. Is that the case? can someone shade a light on this issue. I'd love to try Segnet on my data and looking forward to a solution other than compiling an old and deprecated caffe version

**Comment by sepidehhosseinzadeh** [comment]
Hi @alexgkendall  I have caffe-segnet installed for the link, and I cmake it successfully, but I am having the error:

Building BN calc net...
Traceback (most recent call last):
  File "Scripts/compute_bn_statistics.py", line 171, in <module>
    testable_msg = make_testable(args.train_model)
  File "Scripts/compute_bn_statistics.py", line 35, in make_testable
    text_format.Merge(train_str, train_net)
  File "/usr/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 158, in Merge
    _MergeField(tokenizer, message)
  File "/usr/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 236, in _MergeField
    _MergeField(tokenizer, sub_message)
  File "/usr/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 210, in _MergeField
    message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 7:3 : Message type "caffe.LayerParameter" has no field named "dense_image_data_param".

Could you please help me?

**Comment by liruoteng** [comment]
Hi, @sepidehhosseinzadeh  , I have exactly the same problem as yours, but I have solved this problem by changing the path setting of caffe-segnet . i.e. In compute_bn_statisitcs.py: line 10. caffe_root = "<your path here>" 

Please check your path setting again to make sure this python script could locate the correct caffe root direction. 

Hope it helps

**Comment by mjohn123** [comment]
For all, I think I solved that issue by changed the path in file compute_bn_statistics.py (line 10)
We just add the dot before the path. This is my solution
`caffe_root = '/SegNet/caffe-segnet/'` 	 to `caffe_root = './SegNet/caffe-segnet/'`

**Comment by ronalddas** [comment]
Even i am facing the same error, but i am using the new version which support cudnn [v5(.](https://github.com/TimoSaemann/caffe-segnet-cudnn5) So i guess the functions are deprecated

**Comment by tebdrepo** [comment]
Hi , 
I am also getting the error 
:Message type "caffe.LayerParameter" has no field named "dense_image_data_param".
Please guide how to resolve ...earlier post didn’t helped me .I am new to caffe

**Comment by su526664687** [comment]
Note: root should end with '/'

**Comment by mustafaghali** [comment]
@mjohn123 what is the path of compute_bn_statistics.py file ?

**Comment by momozizi** [comment]
Hi ,
I am also getting the error:
Message type "caffe.LayerParameter" has no field named "upsample_param"
Please guide how to resolve ...earlier post didn’t helped me .I am new to caffe

**Comment by jeya-maria-jose** [comment]
@annie-z , I too had the same error, it was resolved by placing the freshly installing caffe-segnet file as given in the link and using the proper command directory while execution
