### ISSUE TITLE
Failed to parse NetParameter file: ./SegNet/Models/VGG_ILSVRC_16_layers.caffemodel

### ISSUE THREAD

**Issue by albertxavier001** [alexgkendall/SegNet-Tutorial#40]
Hi,
I download weights of VGG and use the 3rd command `./SegNet/caffe-segnet/build/tools/caffe train -gpu 0 -solver /SegNet/Models/segnet_solver.prototxt -weights /SegNet/Models/VGG_ILSVRC_16_layers.caffemodel  # This will begin training SegNet on GPU 0 with a pretrained encoder`, but I got this error:

> I0531 10:46:46.326437 12574 caffe.cpp:86] Finetuning from ./SegNet/Models/VGG_ILSVRC_16_layers.caffemodel
F0531 10:46:46.480464 12574 upgrade_proto.cpp:935] Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: ./SegNet/Models/VGG_ILSVRC_16_layers.caffemodel
*** Check failure stack trace: ***
    @     0x7fa3a96d9d7d  google::LogMessage::Fail()
    @     0x7fa3a96dbc1d  google::LogMessage::SendToLog()
    @     0x7fa3a96d9998  google::LogMessage::Flush()
    @     0x7fa3a96dc47e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fa3a9a76a37  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7fa3a9b5f51a  caffe::Net<>::CopyTrainedLayersFrom()
    @           0x407e0e  CopyLayers()
    @           0x4082d5  train()
    @           0x406178  main
    @     0x7fa3a8bdea40  (unknown)
    @           0x406559  _start
Aborted (core dumped)

**Comment by albertxavier001** [comment]
I download [http://dl.caffe.berkeleyvision.org/bvlc_reference_caffenet.caffemodel](url) and it can be parsed. But I cannot train since my GPU memory is too small (3GB). I set bach_size to 1 but still out of memory.

**Comment by alexgkendall** [comment]
You should use this file and ensure you reference it in the correct directory
http://www.robots.ox.ac.uk/~vgg/software/very_deep/caffe/VGG_ILSVRC_16_layers.caffemodel

**Comment by albertxavier001** [comment]
Thanks. I finally found my caffemodel was imcomplete.
