### ISSUE TITLE
How much GPU memory required for SegNet basic version

### ISSUE THREAD

**Issue by Crefeda** [alexgkendall/SegNet-Tutorial#5]
Hi I wanted to know how much GPU memory is required for SegNet basic version as I want to know how to fix the batch size.

**Comment by alexgkendall** [comment]
You would probably need a GPU with 2GB of memory as absolute minimum. Memory use depends on:
1) model size
2) batch size
3) image size
So you can tweak these three things to fit on whatever hardware you have available.
