### ISSUE TITLE
Calculating Accuracy for SegNet

### ISSUE THREAD

**Issue by Almo1982** [alexgkendall/SegNet-Tutorial#50]
Hi all,

i trained a couple of SegNet Nets so far, everything works fine testing my models with the test_segmentation.py file that shows me the results visually.
I am wondering how i can calculate the Global, Class an Mean I/U accuracy values like shown in the table of the results in the tutorial? I know the formula for this with the TP, TN, FP and FN meanings, but do i have to write a script by myself or is there anything coming with SegNet i didnt recognize so far?

Thank you!
Stefan

**Comment by alexgkendall** [comment]
Hey Stefan,

When writing the SegNet papers I was using the matlab script here:
https://github.com/alexgkendall/SegNet-Tutorial/blob/master/Scripts/compute_test_results.m 

However a direct evaluation in python would make more sense!

Alex

**Comment by Almo1982** [comment]
Hi Alex,

thank you for your Feedback!

Yes, in the meantime i realized this matlab-script and i was already able to run it with my own predictions of a custom dataset.

I will close this issue then.

Thanks!
Stefan

**Comment by ArunJ1** [comment]
> Hi Alex,
> 
> thank you for your Feedback!
> 
> Yes, in the meantime i realized this matlab-script and i was already able to run it with my own predictions of a custom dataset.
> 
> I will close this issue then.
> 
> Thanks!
> Stefan

Can you pls provide the Python code???

**Comment by Alice-kenan** [comment]
hey
I trained segnet on camvid dataset, and got the acc by Scripts/compute_test_results.m.
The global acc is great(>0.9), but  the other acc is too low( about 0.15), I don't know the reason about it, Can you help me?
thanks.
