### ISSUE TITLE
Can't open segnet weight file?

### ISSUE THREAD

**Issue by Primus-zhao** [alexgkendall/SegNet-Tutorial#52]
Hi, appreciate that you share all your code in git, but got one problem when i try to repeat the demo.
The weights file of link: http://mi.eng.cam.ac.uk/~agk34/resources/SegNet/segnet_weights_driving_webdemo.caffemodel   can't be opened by the caffe.Net. The traceback is as following:
python Scripts/webcam_demo.py --model Example_Models/segnet_model_driving_webdemo.prototxt --weights /Example_Models/segnet_weights_driving_webdemo.caffemodel --colours /Scripts/camvid12.png
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0721 09:17:41.122994  3997 _caffe.cpp:122] DEPRECATION WARNING - deprecated use of Python interface
W0721 09:17:41.123042  3997 _caffe.cpp:123] Use this instead (with the named "weights" parameter):
W0721 09:17:41.123049  3997 _caffe.cpp:125] Net('Example_Models/segnet_model_driving_webdemo.prototxt', 1, weights='/Example_Models/segnet_weights_driving_webdemo.caffemodel')
Traceback (most recent call last):
  File "Scripts/webcam_demo.py", line 28, in <module>
    caffe.TEST)
RuntimeError: Could not open file /Example_Models/segnet_weights_driving_webdemo.caffemodel
After that i opened the caffemodel file with sublime text and found that instead of hex digits, there are lots of error codes. Could you help me to figure out?

**Comment by Primus-zhao** [comment]
@alexgkendall ,

just find that weights download doesn't support linux terminal and firefox, perfectly solved after changing to chrome.

**Comment by WeiyiLi** [comment]
@Primus-zhao Hello! I got the exact same problem on the unreadable hex digits of .caffemodel file. I was using Ubuntu 14.04 and changed to use chrome to download the weights file, but the downloaded file is still hex digits....Did you just open the chrome and type the weight file link? If so, do you know why I still got this strange file and how can I fix it? Thank you so much!

**Comment by chaneydd** [comment]
hi,,could you please describe your solution in detail,  I met the same problem. I ran the a python program in the linux terminal @Primus-zhao

**Comment by Ruslan1990** [comment]
Try to remove "/" before Example_Models/segnet_weights_driving_webdemo.caffemodel

Same thing to Scripts/camvid12.png

**Comment by kerolos** [comment]
Could you Please let me know how did you fix this error? @Primus-zhao , @chaneydd , @Ruslan1990 .
I also Changed the directory but it doesn't help.
