### ISSUE TITLE
Problem when using weights with pycaffe

### ISSUE THREAD

**Issue by Simon-Prevoteaux** [alexgkendall/SegNet-Tutorial#54]
Hi,

For one of my project, I have trained a Segnet using my own labeled image extracted from this dataset [https://sites.google.com/site/fashionparsing/dataset](url). I had to reshape the image because I only have 4Go GPU but i checked everything, and my label values are correct, and so are my images.

To debug the training, I have decided tu run it on a single image and overfit on this, and then use this same image for testing, which should result in a quite good segmentation.

However, after training on a single image up to 95% of accuracy, and using the weights from this iteration in a simple python script slighly modified from test_segmentation_camvid.py, the output of the test using this same image is very bad, and after a lot of training iterations, the output of the test is a one-classe image.

Note that I have tuned the upsampling parameters, checked that my number of output was correct. I have even tried to learn the model from a script and share the weights with the inference model, but doesn't work either. I'm working on an amazon machine g2.2xlarge with 4Go GPU, maybe thats the problem.
I would really appreciate if someone facing the same problem could give me a piece of advice.

Thank you.

**Comment by Raj7kumar7** [comment]
@Simon-Prevoteaux How can i train segnet  using my own label image?
Can you tell me the steps..

Thanks
