### ISSUE TITLE
regarding two or multiple convolutional layers connecting with each other before a max pooling layer

### ISSUE THREAD

**Issue by surfreta** [alexgkendall/SegNet-Tutorial#76]
Hello, in accordance with the Segnet architecture, there are two convolutional layers connecting with each other befor attaching another maxpooling layer in each building block, as shown in the following figure. I am not very clear about the logic of designing this way. Why just having a larger convolution layers combining two. What are the real advantage of having several convolutional layers sequentially in each block.

![capture](https://cloud.githubusercontent.com/assets/23064201/22889341/69572b5c-f1ce-11e6-90aa-7718de9b7f54.JPG)

**Comment by TimoSaemann** [comment]
After each conv layer follows a ReLU layer. In this way you include more non-linearities (ReLU), which gives the network more power (roughly said).
