### ISSUE TITLE
Check failed: ShapeEquals(proto) shape mismatch (reshape not set)

### ISSUE THREAD

**Issue by baristahell** [alexgkendall/SegNet-Tutorial#78]
Hello
I'm trying to simply make predictions (not a real testing phase with labeled data) with the `segnet_iter_30000_timo.caffemodel` model **in python**.
For that, i changed the net prototxt, removing the data and the loss layers to get a "deploy" version.
I also added 
> input: "data"
> input_dim: 1
> input_dim: 3
> input_dim: 360
> input_dim: 480

at the beggining of the prototxt to shape the data blob so i can resize the input images at this size.

But at the end of `net = caffe.Net(args.model, args.weights, caffe.TEST)` (after Network initialization done.Memory required for data: 1063756800) i get the error in the title. 
Does anyone know what's going on? Do i have to manually resize the input/blobs?

Thank you.

**Comment by TimoSaemann** [comment]
Hi, 
Have you tried it with the "segnet_inference.prototxt"? That file is for testing.

**Comment by baristahell** [comment]
Well i was trying to use pycaffe with
>out = net.forward_all(data=input_image)
so without using the txt file in the net definition, and i don't really know what i have to change to change my data source. I'd like to ba able to load the net and then feed it with images on disk.

**Comment by baristahell** [comment]
I made it work like i wanted, closing the issue.
