### ISSUE TITLE
No labeled Images?

### ISSUE THREAD

**Issue by jmtatsch** [alexgkendall/SegNet-Tutorial#8]
Hi Alex,

when I follow your tutorial, I cannot train a model because the filenames in train.txt have changed.
In fact there don't seem to be any labeled images at all ... everything should be included in the repository, right?

**Comment by alexgkendall** [comment]
Hey sorry about that! I've just pushed a fix to the repository, does it work for you now? The data should have all been there, the paths in train.txt, test.txt, val.txt were just incorrect

**Comment by jmtatsch** [comment]
Ahh, those are the labels. At first glance they seemed all black to me :P Should work now, will give it a try tomorrow...
